## Singleton managing central data across application providing several functions:
## - Creates/stores PlayerData for the current run along with helper methods for retrieving common PlayerData queries.
## - Stores read only data and prototype data lookup tables with getters methods for each.
## - Maintains schema
## - Stores cache of generated objects

## NOTE: See GlobalTestDataGenerator and GlobalProdDataGenerator for testing and production data management
extends Node

#region Schema and Data Management

## A lookup table used to generate other lookup tables via Global._generate_schema() and
## FileLoader._generate_base_mod_data(), which are used for schema management across the framework.
## CRITICAL: Global._generate_schema() MUST be run before any other data related methods, at the top
## of Global._ready().
## WARNING: Any time a new kind of data is added to the schema you should update this table and also run
## FileLoader._generate_base_mod_data() in _ready().
@onready var SCHEMA: Array[Array] = [
	# ["SerializableDataScriptNameAsString", SerializableDataScript, "lookup_table_property_name", ["optional external folder paths to read from", ...]],
	# read only data
	["RestActionData", RestActionData, "_id_to_rest_action_data", ["rest_actions/"]],
	["StatusEffectData", StatusEffectData, "_id_to_status_data", ["status_effects/"]],
	["ConsumableData", ConsumableData, "_id_to_consumable_data", ["consumables/"]],
	["CardDecoratorData", CardDecoratorData, "_id_to_card_decorator_data", ["card_decorators/"]],
	["ActData", ActData, "_id_to_act_data", ["acts/"]],
	["EventData", EventData, "_id_to_event_data", ["events/"]],
	["EventPoolData", EventPoolData, "_id_to_event_pool_data", ["event_pools/"]],
	["DialogueData", DialogueData, "_id_to_dialogue_data", ["dialogue/"]],
	["ActionInterceptorData", ActionInterceptorData, "_id_to_action_interceptor_data", ["action_interceptors/"]],
	["ColorData", ColorData, "_id_to_color_data", ["colors/"]],
	["KeywordData", KeywordData, "_id_to_keyword_data", ["keywords/"]],
	["CharacterData", CharacterData, "_id_to_character_data", ["characters/"]],
	["AnimationData", AnimationData, "_id_to_animation_data", ["animations/"]],
	["RunModifierData", RunModifierData, "_id_to_run_modifier_data", ["run_modifiers/"]],
	["RunStartOptionData", RunStartOptionData, "_id_to_run_start_option_data", ["run_start_options/"]],
	["CardPackData", CardPackData, "_id_to_card_pack_data", ["card_packs/"]],
	["ArtifactPackData", ArtifactPackData, "_id_to_artifact_pack_data", ["artifact_packs/"]],
	["ConsumablePackData", ConsumablePackData, "_id_to_consumable_pack_data", ["consumable_packs/"]],
	["CustomUIData", CustomUIData, "_id_to_custom_ui_data", ["custom_ui/"]],
	["CustomSignalData", CustomSignalData, "_id_to_custom_signal_data", ["custom_signals/"]],
	# prototype data
	["EnemyData", EnemyData,"_id_to_enemy_data", ["enemies/"]],
	["CardData", CardData, "_id_to_card_data", ["cards/"]],
	["ArtifactData", ArtifactData, "_id_to_artifact_data", ["artifacts/"]],
	["PlayerData", PlayerData, "_id_to_player_data", ["player/"]],
]

## These lookup tables allow for automating the process of loading, saving, and mapping data
## across the application rather than writing tons of parallel save/load/register functions.
## WARNING: This is generated by _generate_schema(). Do not manually enter into this.
var CLASS_NAME_TO_CLASS: Dictionary[String, Script] = {
	#"SerializeableData": SerializableData,
}

## Maps a SerializeableData class Script to the lookup table it corresponds to. Used for register_rod()
## WARNING: This is generated by _generate_schema(). Do not manually enter into this.
var READ_ONLY_GETTER_SCHEMA: Dictionary[Script, String] = {
	#SerializableData, "id_to_data"
}

# immutable data lookup tables. Do not modify their contents after creation
var _id_to_rest_action_data: Dictionary[String, RestActionData] = {}
var _id_to_status_data: Dictionary[String, StatusEffectData] = {}
var _id_to_consumable_data: Dictionary[String, ConsumableData] = {}
var _id_to_card_decorator_data: Dictionary[String, CardDecoratorData] = {}
var _id_to_act_data: Dictionary[String, ActData] = {}
var _id_to_event_data: Dictionary[String, EventData] = {}
var _id_to_event_pool_data: Dictionary[String, EventPoolData] = {}
var _id_to_dialogue_data: Dictionary[String, DialogueData] = {}
var _id_to_action_interceptor_data: Dictionary[String, ActionInterceptorData] = {}
var _id_to_color_data: Dictionary[String, ColorData] = {}
var _id_to_keyword_data: Dictionary[String, KeywordData] = {}
var _id_to_character_data: Dictionary[String, CharacterData] = {}
var _id_to_animation_data: Dictionary[String, AnimationData] = {}
var _id_to_run_modifier_data: Dictionary[String, RunModifierData] = {}
var _id_to_run_start_option_data: Dictionary[String, RunStartOptionData] = {}
var _id_to_card_pack_data: Dictionary[String, CardPackData] = {}
var _id_to_artifact_pack_data: Dictionary[String, ArtifactPackData] = {}
var _id_to_consumable_pack_data: Dictionary[String, ConsumablePackData] = {}
var _id_to_custom_ui_data: Dictionary[String, CustomUIData] = {}
var _id_to_custom_signal_data: Dictionary[String, CustomSignalData] = {}

# prototyped data; Read only data that are duplicated into mutable data instances
var _id_to_enemy_data: Dictionary[String, EnemyData] = {}
var _id_to_card_data: Dictionary[String, CardData] = {}
var _id_to_artifact_data: Dictionary[String, ArtifactData] = {}
var _id_to_player_data: Dictionary[String, PlayerData] = {}

# mutable data; These objects are modifiable
var player_data: PlayerData = PlayerData.new() # the current run. prototype instance.
var user_settings_data: UserSettingsData = UserSettingsData.new() # the user's settings
var profile_data: ProfileData = ProfileData.new()
var is_run: bool = false # simple flag to check if a run is currently happening

## The RunModifierData object ids for standard difficulty modifiers, allowing for a difficulty select
## on the new run menu.
## Defined either through GlobalTestGeneratorData or GlobalProdGeneratorData add_(test)_run_modifiers().
var STANDARD_DIFFICULTY_RUN_MODIFIER_IDS: Array[String] = [ 
	#"run_modifier_difficulty_1", "run_modifier_difficulty_2", "run_modifier_difficulty_3",
	#"run_modifier_difficulty_4", "run_modifier_difficulty_5",
]

#region cached objects
## Stores caches of card filter results, making complicated repeated searches across
## potentially thousands of cards more performant and organized
## These typically correspond to CardPackData object ids, but others may be added.
## See: Global._generate_card_pack_cache()
var _id_to_card_filter_cache: Dictionary[String, CardFilter] = {}

## Stores caches of artifact filter results.
## See: Global._generate_artifact_pack_cache()
var _id_to_artifact_filter_cache: Dictionary[String, ArtifactFilter] = {}

## Stores caches of consumable filter results.
## See: Global._generate_consumable_pack_cache()
var _id_to_consumable_filter_cache: Dictionary[String, ConsumableFilter] = {}
#endregion

## Takes SCHEMA and generates fast lookup tables used for mapping data types
## in the framework. This automates and centralizes a lot of extremely tedious
## schema maintenance and enables useful behavior like register_rod() for test data generation,
## and file/mod loading through data table mapping.
func _generate_schema() -> void:
	for schema_row: Array in SCHEMA:
		var data_script_string: String = schema_row[0]
		var data_script: Script = schema_row[1]
		var data_lookup_table_property_name: String = schema_row[2]
		var read_only_data_folder_paths: Array[String] = []
		read_only_data_folder_paths.assign(schema_row[3])
		
		READ_ONLY_GETTER_SCHEMA[data_script] = data_lookup_table_property_name
		CLASS_NAME_TO_CLASS[data_script_string] = data_script

## Allows for automatically registering a Read-Only-Data object into its proper lookup table. This is extremely
## useful for generic data pipelines, and streamlines test data code. See READ_ONLY_GETTER_SCHEMA.
func register_rod(serializeable_data: SerializableData, allow_collisions: bool = true) -> void:
	var script_class: Script = serializeable_data.get_script() # get the type of the object
	if not READ_ONLY_GETTER_SCHEMA.has(script_class):
		breakpoint
		DebugLogger.log_error("Global.register_rod(): No lookup table for {0}".format([script_class]))
		get_tree().quit()
	else:
		# find the matching lookup table of the SerializeableData
		var lookup_table_property_name: String = READ_ONLY_GETTER_SCHEMA[script_class]
		var lookup_table: Dictionary = get(lookup_table_property_name)
		if serializeable_data.object_id == "":
			breakpoint
			DebugLogger.log_error("Global.register_rod(): Empty object ID")
			get_tree().quit()
		if lookup_table.has(serializeable_data.object_id) and not allow_collisions:
			breakpoint
			DebugLogger.log_error("Global.register_rod(): Object ID collision in {0} for ID: {1}".format([lookup_table_property_name, serializeable_data.object_id]))
			get_tree().quit()
		# register read only object into lookup table
		lookup_table[serializeable_data.object_id] = serializeable_data
		# reassign the lookup table to Global
		set(lookup_table_property_name, lookup_table)

#endregion

func _ready():
	### Schema
	# generate the schema. This must be done before everything else in Global or errors will ensue
	# when loading data or generating test data.
	_generate_schema()
	# make SerializableData make a mapping of global classes of its type to class.
	# this must be done before everything else or you cannot load objects from file.
	SerializableData.build_serializable_script_cache()
	
	### Load Profile and User Settings
	FileLoader.load_profile()
	FileLoader.load_user_settings()
	
	### Production data generation
	#GlobalProdDataGenerator.generate_production_data()
	#ProfileData.ENABLE_ALL_DIFFICULTIES = false
	
	### Test data generation
	GlobalTestDataGenerator.generate_test_data()
	
	### Testing flags
	ProfileData.ENABLE_ALL_DIFFICULTIES = true
	StatsHandler.TRACK_RUN_HISTORY = true
	
	### Modding and external file loads
	#FileLoader._generate_mod_list_data() # generates the mod list used for loading ALL external files
	#FileLoader._generate_base_mod_data() # generates mod data for base game. uncomment, run once, then comment back after updating SCHEMA
	FileLoader.load_read_only_data() # loads all mods and base game exteral data
	
	### Generated from loaded data
	# custom signals generated from CustomSignalData
	Signals.register_all_custom_signals()
	# generate cached filters from CardPackData
	Global._generate_card_pack_cache()
	# generate cached filters from ArtifactPackData
	Global._generate_artifact_pack_cache()
	# generate cached filters from ConsumablePackData
	Global._generate_consumable_pack_cache()
	# force generate all animations
	FileLoader.generate_all_animations()
	
	### Exporting Data
	# FileLoader.export_read_only_data() # uncomment to output all unexported test data to file


#region Run
## Starts a new run under a given seed with a given character
func start_run(character_object_id: String, run_seed: int, difficulty_level: int = 0, custom_run_modifier_object_ids: Array[String] = []) -> void:
	var character_data: CharacterData = get_character_data(character_object_id)
	
	# initialize player data from a prototype using selected character
	player_data = get_player_data_from_prototype(character_data.character_player_id)
	is_run = true # run is considered started
	
	# initialize run rng
	player_data.player_run_seed = run_seed
	
	#region Run Data Initialization
	# generate artifact pool for the run
	# NOTE: This holds all artifacts, regardless of packs
	player_data.initialize_artifact_pool()
	
	# add starting artifacts to player
	for artifact_id in character_data.character_starting_artifact_ids:
		player_data.add_artifact(artifact_id)
	
	# add starting cards to player
	for card_object_id in character_data.character_starting_card_object_ids:
		player_data.player_deck.append(get_card_data_from_prototype(card_object_id))
	
	# card draft
	player_data.reward_draft_card_pack_ids.assign(character_data.character_starting_card_draft_card_pack_ids)
	# artifact draft
	player_data.player_artifact_pack_ids.assign(character_data.character_starting_artifact_pack_ids)
	# consumable draft
	player_data.player_consumable_pack_ids.assign(character_data.character_starting_consumable_pack_ids)
	
	# money and health
	player_data.player_money = character_data.character_starting_money
	player_data.player_health_max = character_data.character_starting_health
	player_data.player_health = character_data.character_starting_health
	
	# location, act, and difficult
	player_data.player_location_id = "location_0" # hardcoded starting location
	player_data.player_act = 1
	player_data.player_run_difficulty_level = difficulty_level
	
	# determine the run modifiers
	player_data.player_run_modifier_object_ids = []
	# automatic run modifiers
	for run_modifier_id: String in Global._id_to_run_modifier_data:
		var run_modifier_data: RunModifierData = Global.get_run_modifier_data(run_modifier_id)
		if run_modifier_data.run_modifier_is_automatic:
			player_data.player_run_modifier_object_ids.append(run_modifier_id)
	# difficulty run modifiers
	if difficulty_level > 0:
		var difficulty_amount_max: int = min(difficulty_level, len(STANDARD_DIFFICULTY_RUN_MODIFIER_IDS))
		player_data.player_run_modifier_object_ids += STANDARD_DIFFICULTY_RUN_MODIFIER_IDS.slice(0, difficulty_amount_max, 1, true)
	player_data.player_run_modifier_object_ids += custom_run_modifier_object_ids
	#endregion
	
	# Run Stats
	player_data.player_run_stats = RunStatsData.new()
	StatsHandler.current_run_stats = player_data.player_run_stats # update reference
	
	
	# Uncomment these for adding test stuff to the player
	# GlobalTestDataGenerator.add_test_cards_to_player_deck()
	# GlobalTestDataGenerator.add_test_artifacts_to_player()
	# GlobalTestDataGenerator.add_test_consumables_to_player()
	
	# connect signals and generate caches
	player_data.init()
	
	# run modifiers
	perform_start_of_run_modifiers()
	
	# generate world
	ActionGenerator.generate_act("act_1", true)
	
	# save immediately at start of run
	FileLoader.autosave()
	
	Signals.run_started.emit()
	Signals.map_location_selected.emit(get_player_location_data())	# simulate visiting the first location
	
	# simulate a win
	#await get_tree().create_timer(5).timeout
	#Signals.run_victory.emit()

## Used for end_run().
enum RUN_ENDS {QUIT, LOSS, VICTORY}

## Ends the player's current run under the given status.
func end_run(run_end_state: int = RUN_ENDS.QUIT) -> void:
	match run_end_state:
		RUN_ENDS.QUIT:
			pass # no changes, run should be autosaved already
		RUN_ENDS.LOSS:
			FileLoader.delete_save()
			StatsHandler.lose_run() # store loss in profile
			FileLoader.save_profile()
		RUN_ENDS.VICTORY:
			FileLoader.delete_save()
			StatsHandler.win_run() # store win in profile
			FileLoader.save_profile()
	
	is_run = false
	Signals.run_ended.emit()

## Stores a loss in the player's profile and deletes save, without starting a new run
func forfeit_run_from_title() -> void:
	FileLoader.load_game(false)
	FileLoader.delete_save()
	StatsHandler.lose_run()
	FileLoader.save_profile()

## Returns whether the run should end or not
func is_end_of_run() -> bool:
	if not is_end_of_act():
		return false # more locations ahead
	if player_data.player_act_max <= 0:
		return false # endless mode
	if player_data.player_act < player_data.player_act_max:
		return false # more acts ahead
	return true

## Performs any custom logic for each modifier done at the very beginning of a run
func perform_start_of_run_modifiers() -> void:
	for run_modifier_object_id in Global.player_data.player_run_modifier_object_ids:
		var run_modifier_data: RunModifierData = Global.get_run_modifier_data(run_modifier_object_id)
		if run_modifier_data == null:
			DebugLogger.log_error("Global.perform_start_of_run_modifiers(): No RunData with id of \"{0}\"".format([run_modifier_object_id]))
			continue
		else:
			var run_modifier_modifier_script_path: String = run_modifier_data.run_modifier_modifier_script_path
			if run_modifier_modifier_script_path != "":
				var run_modidifier_script_asset = load(run_modifier_modifier_script_path)
				var run_modifier: BaseRunModifier = run_modidifier_script_asset.new()
				run_modifier.run_start_modification()

func pause_game() -> void:
	get_tree().paused = true
	Signals.game_paused.emit()
	
func unpause_game() -> void:
	get_tree().paused = false
	Signals.game_unpaused.emit()

#endregion

#region Combat and Combat Stats
## Gets the BaseCombatant representing the player character
func get_player() -> Player:
	return Global.get_tree().get_first_node_in_group("players")

func get_alive_enemies() -> Array[Enemy]:
	var returned_enemies: Array[Enemy] = []
	for enemy: Enemy in Global.get_tree().get_nodes_in_group("enemies_alive_or_dead"):
		if enemy.is_alive():
			returned_enemies.append(enemy)
	return returned_enemies

func are_remaining_enemies() -> bool:
	return len(get_alive_enemies()) > 0

func get_combat_stats() -> CombatStatsData:
	# shorthand helper method
	# gets player's combat stats for this combat
	return StatsHandler.current_combat_stats
	
func get_run_stats() -> RunStatsData:
	# shorthand helper method
	return player_data.player_run_stats
	
func is_player_in_combat() -> bool:
	return StatsHandler.current_combat_stats != null

func is_player_turn() -> bool:
	return StatsHandler.is_player_turn

#endregion

#region Artifacts
func get_artifact_data(artifact_id: String) -> ArtifactData:
	return _id_to_artifact_data.get(artifact_id, null)

func get_all_artifacts() -> Array[ArtifactData]:
	var all_artifacts: Array[ArtifactData] = []
	all_artifacts.assign(_id_to_artifact_data.values())
	return all_artifacts

func get_artifact_data_from_prototype(artifact_id: String) -> ArtifactData:
	# generates a copy of a given ArtifactData
	var artifact_data: ArtifactData = get_artifact_data(artifact_id)
	return artifact_data.get_prototype(true)
#endregion

#region Consumables
func get_consumable_data(consumable_object_id: String) -> ConsumableData:
	return _id_to_consumable_data.get(consumable_object_id, null)

func get_all_consumables() -> Array[ConsumableData]:
	var all_consumables: Array[ConsumableData] = []
	all_consumables.assign(_id_to_consumable_data.values())
	return all_consumables

func get_player_consumable_in_slot_index(consumable_slot_index: int) -> ConsumableData:
	return player_data.get_consumable_in_slot(consumable_slot_index)
#endregion

#region Card Decorators
func get_card_decorator_data(card_decorator_object_id: String) -> CardDecoratorData:
	return _id_to_card_decorator_data.get(card_decorator_object_id, null)
#endregion

#region Rest Actions
func get_rest_action_data(rest_action_object_id: String) -> RestActionData:
	return _id_to_rest_action_data.get(rest_action_object_id, null)
#endregion

#region Status Effects
func get_status_effect_data(status_effect_object_id: String) -> StatusEffectData:
	return _id_to_status_data.get(status_effect_object_id, null)
#endregion

#region Acts
func get_act_data(act_id: String) -> ActData:
	return _id_to_act_data[act_id]
#endregion
	
#region Events and Event Pools
func get_event_data(event_object_id: String) -> EventData:
	return _id_to_event_data.get(event_object_id, null)

func get_player_event_data() -> EventData:
	# gets the event at the player's current location
	# this will typically generate a new event at the location, via LocationData.get_location_event_object_id()
	var player_location_data: LocationData = get_player_location_data()
	var location_event_object_id: String = player_location_data.get_location_event_object_id()
	return get_event_data(location_event_object_id)

func get_event_pool_data(event_pool_object_id: String) -> EventPoolData:
	return _id_to_event_pool_data.get(event_pool_object_id, null)
#endregion

#region Dialogue
func get_dialogue_data(dialogue_object_id: String) -> DialogueData:
	return _id_to_dialogue_data.get(dialogue_object_id, null)
#endregion

#region Action Interceptors
func get_action_interceptor_data(action_interceptor_object_id: String) -> ActionInterceptorData:
	return _id_to_action_interceptor_data.get(action_interceptor_object_id, null)
#endregion

#region Colors
func get_color_data(color_id: String) -> ColorData:
	return _id_to_color_data.get(color_id)
#endregion

#region Keywords
func get_keyword_data(keyword_object_id: String) -> KeywordData:
	return _id_to_keyword_data.get(keyword_object_id, null)
#endregion

#region Characters
func get_character_data(character_object_id: String) -> CharacterData:
	return _id_to_character_data.get(character_object_id, null)

func get_player_character_data() -> CharacterData:
	# gets the character data that the current player is playing as
	var character_data: CharacterData = get_character_data(player_data.player_character_object_id)
	return character_data
#endregion

#region Animations
func get_animation_data(animation_object_id: String) -> AnimationData:
	return _id_to_animation_data.get(animation_object_id, null)

#endregion

#region Run Modifiers
func get_run_modifier_data(run_modifier_object_id: String) -> RunModifierData:
	return _id_to_run_modifier_data.get(run_modifier_object_id, null)
#endregion

#region Run Start Options
func get_run_start_option_data(run_start_option_object_id: String) -> RunStartOptionData:
	return _id_to_run_start_option_data.get(run_start_option_object_id, null)
#endregion

#region Custom UI
func get_custom_ui_data(custom_ui_object_id: String) -> CustomUIData:
	return _id_to_custom_ui_data.get(custom_ui_object_id, null)
#endregion

#region Custom Signals
func get_custom_signal_data(custom_signal_object_id: String) -> CustomSignalData:
	return _id_to_custom_signal_data.get(custom_signal_object_id, null)
#endregion

#region Locations
func get_location_data(location_id: String) -> LocationData:
	return player_data.location_id_to_location_data.get(location_id, null)

func get_all_locations() -> Array[LocationData]:
	var locations: Array[LocationData] = []
	for location in player_data.location_id_to_location_data.values():
		locations.append(location)
	return locations

func get_all_act_locations() -> Array[LocationData]:
	# gets all locations in the player's act
	var locations: Array[LocationData] = []
	for location in player_data.location_id_to_location_data.values():
		if location.location_act == player_data.player_act:
			locations.append(location)
	return locations

func get_player_current_floor() -> int:
	# derive floor from the current location's floor number
	var current_location_data: LocationData = Global.get_player_location_data()
	if current_location_data == null:
		breakpoint
		return -1
	return current_location_data.location_floor

func get_player_location_data() -> LocationData:
	return get_location_data(player_data.player_location_id)

func get_next_locations(location_id: String = player_data.player_location_id) -> Array[LocationData]:
	# helper method to get the locations after a given one
	# defaults to player's location
	var next_locations: Array[LocationData] = []
	
	var current_location_data: LocationData = get_location_data(location_id)
	
	if current_location_data == null:
		breakpoint
		return []
		
	for next_location_id in current_location_data.location_next_location_ids:
		var next_location_data: LocationData = get_location_data(next_location_id)
		next_locations.append(next_location_data)
	
	return next_locations

func is_end_of_act() -> bool:
	return len(get_next_locations()) == 0

func clear_locations() -> void:
	player_data.location_id_to_location_data.clear()
#endregion

#region Shops
## Creates a new shop and assigns it the player's location
func generate_shop_at_player_location() -> ShopData:
	var location_data: LocationData = Global.get_player_location_data()
	var shop_data: ShopData = ShopData.new()
	shop_data.shop_location_id = location_data.location_id
	player_data.player_shop_data = shop_data
	return shop_data
	
## Gets the player's shop data if the shop matches the player data. This is used to check against
## old shops at a previous location.
func get_shop_at_player_location() -> ShopData:
	var player_shop_data: ShopData = Global.player_data.player_shop_data
	var player_location_data: LocationData = get_player_location_data()
	# no shop
	if player_shop_data == null:
		return null
	# shop not at current location
	if player_shop_data.shop_location_id != player_location_data.location_id:
		return null
	
	return player_shop_data
#endregion

#region Enemies
func get_enemy_data(enemy_object_id: String) -> EnemyData:
	return _id_to_enemy_data.get(enemy_object_id, null)

func get_enemy_data_from_prototype(enemy_object_id: String) -> EnemyData:
	# generates a copy of a given EnemyData
	var enemy_data: EnemyData = get_enemy_data(enemy_object_id)
	return enemy_data.get_prototype(true)
#endregion

#region Player Data Prototypes

func get_player_data_from_prototype(player_id: String) -> PlayerData:
	var _player_data: PlayerData = _id_to_player_data[player_id]
	return _player_data.get_prototype(true)

#endregion

#region Cards
## Gets the data of a read only card data template.
## Use get_card_data_from_prototype() to make an editable copy
func get_card_data(card_object_id: String) -> CardData:
	return _id_to_card_data.get(card_object_id, null)

func get_all_cards() -> Array[CardData]:
	var all_cards: Array[CardData] = []
	for card_data in _id_to_card_data.values():
		all_cards.append(card_data)
	return all_cards

## Generates a mutable copy of a given read only CardData
func get_card_data_from_prototype(card_object_id: String) -> CardData:
	var card_data: CardData = get_card_data(card_object_id)
	return card_data.get_prototype(true)

## Gets mutable copies of CardData given read only CardData ids
func get_card_data_from_prototypes(card_object_ids: Array[String]) -> Array[CardData]:
	var card_prototypes: Array[CardData] = []
	for card_object_id: String in card_object_ids:
		card_prototypes.append(get_card_data_from_prototype(card_object_id))
	return card_prototypes
#endregion

#region Caches and Packs
func get_card_pack_data(card_pack_object_id: String) -> CardPackData:
	return _id_to_card_pack_data.get(card_pack_object_id, null)

func get_artifact_pack_data(artifact_pack_object_id: String) -> ArtifactPackData:
	return _id_to_artifact_pack_data.get(artifact_pack_object_id, null)

## Uses all loaded CardPackData to generate CardFilters and store them in a cache for reuse. This is
## typically only called once on game start.
func _generate_card_pack_cache() -> void:
	for card_pack_data: CardPackData in Global._id_to_card_pack_data.values():
		var card_filter: CardFilter = card_pack_data.create_card_pack_card_filter()
		card_filter.cache_filter(card_pack_data.object_id)

## NOTE: This method should always be called from CardFilter.cache_filter()
## The ID will typically be the same as a card pack ID, but if card filters are cached from other places
## specific IDs can be added ad hoc.
func cache_card_filter(card_filter_cache_id: String, card_filter: CardFilter) -> void:
	_id_to_card_filter_cache[card_filter_cache_id] = card_filter

func get_cached_card_filter(card_filter_cache_id: String) -> CardFilter:
	return _id_to_card_filter_cache.get(card_filter_cache_id, null)

## Uses all loaded ArtifactPackData to generate ArtifactFilters and store them in a cache for reuse. This is
## typically only called once on game start.
func _generate_artifact_pack_cache() -> void:
	for artifact_pack_data: ArtifactPackData in Global._id_to_artifact_pack_data.values():
		var artifact_filter: ArtifactFilter = artifact_pack_data.create_artifact_pack_artifact_filter()
		artifact_filter.cache_filter(artifact_pack_data.object_id)

## NOTE: This method should always be called from ArtifactFilter.cache_filter()
## The ID will typically be the same as a artifact pack ID, but if artifact filters are cached from other places
## specific IDs can be added ad hoc.
func cache_artifact_filter(artifact_filter_cache_id: String, artifact_filter: ArtifactFilter) -> void:
	_id_to_artifact_filter_cache[artifact_filter_cache_id] = artifact_filter

func get_cached_artifact_filter(artifact_filter_cache_id: String) -> ArtifactFilter:
	return _id_to_artifact_filter_cache.get(artifact_filter_cache_id, null)

## Uses all loaded ConsumablePackData to generate ConsumableFilters and store them in a cache for reuse. This is
## typically only called once on game start.
func _generate_consumable_pack_cache() -> void:
	for consumable_pack_data: ConsumablePackData in Global._id_to_consumable_pack_data.values():
		var consumable_filter: ConsumableFilter = consumable_pack_data.create_consumable_pack_consumable_filter()
		consumable_filter.cache_filter(consumable_pack_data.object_id)

## NOTE: This method should always be called from ConsumableFilter.cache_filter()
## The ID will typically be the same as a consumable pack ID, but if consumable filters are cached from other places
## specific IDs can be added ad hoc.
func cache_consumable_filter(consumable_filter_cache_id: String, consumable_filter: ConsumableFilter) -> void:
	_id_to_consumable_filter_cache[consumable_filter_cache_id] = consumable_filter

func get_cached_consumable_filter(consumable_filter_cache_id: String) -> ConsumableFilter:
	return _id_to_consumable_filter_cache.get(consumable_filter_cache_id, null)
#endregion

#region General Utility
## Returns if all given validators pass. This is used all across framework.
func validate(validators: Array[Dictionary], card_data: CardData = null, action: BaseAction = null) -> bool:
	for validator_data: Dictionary in validators:
		for validator_script_path: String in validator_data:
			var validator_script_asset = load(validator_script_path)
			var validator: BaseValidator = validator_script_asset.new()
			
			var validator_values: Dictionary[String, Variant] = {}
			validator_values.assign(validator_data[validator_script_path]) # assign to force typed dict
			
			if not validator.validate(card_data, action, validator_values):
				return false
	
	return true
#endregion
