## Embedded read only data in EnemyData for a single state of intent.
## NOTE: Providing an identical intent_object_id to a higher difficulty level to an
## EnemyData overrides the intent at those difficulty levels and above.
extends SerializableData
class_name EnemyIntentData

const INTENT_INITIAL: String = "intent_initial"

func _init(intent_object_id: String = "", difficulty_level: int = 0, intent_attack_damage: int = 1, intent_number_of_attacks: int = 1, intent_attack_impact_animation_id: String = "", intent_block: int = 0, intent_audio_path: String = "",
intent_next_intent_weights: Dictionary[String, int] = {}, intent_custom_actions: Array[Dictionary] = [], intent_display_types: Array[int] = []) -> void:
	object_id = intent_object_id
	enemy_intent_overrides_id = intent_object_id
	
	# auto format the intent id with the difficulty at the end. This makes it so you don't need to specifiy different names
	# for the same intent which is tedious and easily broken.
	enemy_intent_difficulty_level = difficulty_level
	if difficulty_level > 0:
		object_id = "{0}_d{1}".format([object_id, difficulty_level])
	
	# use object id to derive the intent name
	# "intent_<intent_name>" -> "Intent Name"
	enemy_intent_name = intent_object_id.replace("intent_", "").replace("_", " ").to_pascal_case()
	
	enemy_intent_attack_damage = intent_attack_damage
	enemy_intent_number_of_attacks = intent_number_of_attacks
	enemy_intent_attack_impact_animation_id = intent_attack_impact_animation_id
	enemy_intent_block = intent_block
	enemy_intent_next_intent_weights = intent_next_intent_weights
	enemy_intent_custom_actions = intent_custom_actions
	enemy_intent_audio_path = intent_audio_path
	
	infer_intent_display_types()

## What the intent is called. Mainly for use in the codex. This is automatically
## derived from intent id on initialization for convenience.
@export var enemy_intent_name: String = ""

enum INTENT_DISPLAY_TYPES {
	ATTACKING, # inferred from enemy_intent_attack_damage > 0
	BLOCKING, # inferred from enemy_intent_block > 0
	# determined from custom actions
	DEBUFFING, # enemy is intending to debuff the player
	BUFFING, # enemy is intending to buff themselves
	SUMMONING # enemy is going to spawn more enemies
	}

## How the intent will be displayed as in the form of itent icons above the enemy.
## Autogenerated in infer_intent_display_values()
## NOTE: These correspond to hardcoded icons in Enemy above their heads.
@export var enemy_intent_display_types: Array[int] = [
	#INTENT_DISPLAY_TYPES.ATTACKING
	]

## This will be the same as the original id supplied in the constructor.
@export var enemy_intent_overrides_id: String = ""
## The difficulty level when this intent will be introduced.
@export var enemy_intent_difficulty_level: int = 0

## How the intent is displayed in the codex. This is autogenerated via generate_intent_display_text(),
## but additional lines may be supplied
@export var returned_bbcode: String = ""

## If any audio provided, will play as an instant action.
## NOTE: If the enemy is attacking, this will play *per attack*. If no attacks are happening, it
## will play once.
@export var enemy_intent_audio_path: String = ""

## If defined, each attack will create this impact animation vfx
@export var enemy_intent_attack_impact_animation_id: String = ""

## How much damage the enemy will perform with each attack.
@export var enemy_intent_attack_damage: int = 0

## Number of attacks the enemy will perform.
@export var enemy_intent_number_of_attacks: int = 1

## How much block the enemy will gain this intent.
@export var enemy_intent_block: int = 0

## Any additional actions the enemy will perform with this intent.
@export var enemy_intent_custom_actions: Array[Dictionary] = []

## Maps an EnemyIntentData object_id in the EnemyData.enemy_intents to the
## random weighted integer chance of the next intent, defining a random walk.
@export var enemy_intent_next_intent_weights: Dictionary[String, int] = {}

## Figures out the display types (overhead symbols) based on intent's parameters and custom actions.
func infer_intent_display_types() -> void:
	# infer blocking display type
	if enemy_intent_block > 0:
		if not enemy_intent_display_types.has(INTENT_DISPLAY_TYPES.BLOCKING):
			enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.BLOCKING)
	
	# infer attacking display type
	if enemy_intent_attack_damage > 0 or enemy_intent_number_of_attacks > 0:
		if not enemy_intent_display_types.has(INTENT_DISPLAY_TYPES.ATTACKING):
			enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.ATTACKING)

	# infer statuses and summons
	for action: Dictionary in enemy_intent_custom_actions:
		for action_script_path: String in action:
			var action_data: Dictionary = action[action_script_path]
			# summons
			if action_script_path == Scripts.ACTION_SUMMON_ENEMIES:
				enemy_intent_display_types.push_front(INTENT_DISPLAY_TYPES.SUMMONING)
			
			# statuses
			if action_script_path == Scripts.ACTION_APPLY_STATUS:
				var action_target: int = action_data.get("target_override", BaseAction.TARGET_OVERRIDES.PLAYER)
				var status_effect_object_id: String = action_data.get("status_effect_object_id", "")
				if status_effect_object_id == "":
					DebugLogger.log_warning("EnemyIntentData: No status_effect_object_id supplied for custom status action")
					breakpoint
					continue
				# determine if buffing self or debuffing player
				var status_effect_data: StatusEffectData = Global.get_status_effect_data(status_effect_object_id)
				# buffing enemies
				if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.BUFF:
					if action_target == BaseAction.TARGET_OVERRIDES.PARENT or action_target == BaseAction.TARGET_OVERRIDES.ALL_ENEMIES:
						if not enemy_intent_display_types.has(EnemyIntentData.INTENT_DISPLAY_TYPES.BUFFING):
							enemy_intent_display_types.append(EnemyIntentData.INTENT_DISPLAY_TYPES.BUFFING)
				# debuffing player
				if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.DEBUFF:
					if action_target == BaseAction.TARGET_OVERRIDES.PLAYER:
						if not enemy_intent_display_types.has(EnemyIntentData.INTENT_DISPLAY_TYPES.DEBUFFING):
							enemy_intent_display_types.append(EnemyIntentData.INTENT_DISPLAY_TYPES.DEBUFFING)

## Gets the bbcode needed to display this intent for codex entries.
## NOTE: Extend the bottom section to include more custom action scripts if desired
func get_intent_codex_bbcode() -> String:
	const BBCODE_EMBEDDED_IMAGE_WIDTH: int = 24 # used for statuses and other icons
	var returned_bbcode: String = ""
	
	# blocking
	if enemy_intent_block > 0:
		# add to text
		returned_bbcode += "Gain {0} Block".format([enemy_intent_block])
	
	# attacking
	if enemy_intent_attack_damage > 0 or enemy_intent_number_of_attacks > 0:
		# add to text
		if returned_bbcode.length() > 0:
			returned_bbcode += "\n" # newline
		returned_bbcode += "Do {0} x {1} Damage".format([enemy_intent_attack_damage, enemy_intent_number_of_attacks])
	
	# parse each custom action and use it to generate text from their parameters.
	for action: Dictionary in enemy_intent_custom_actions:
		for action_script_path: String in action:
			var action_data: Dictionary = action[action_script_path]
			match action_script_path:
				# summoning
				Scripts.ACTION_SUMMON_ENEMIES:
					var random_enemy_object_ids: Array[String] = []
					random_enemy_object_ids.assign(action_data.get("random_enemy_object_ids", []))
					# no enemies being summoned
					if len(random_enemy_object_ids) == 0:
						DebugLogger.log_warning("EnemyIntentData: No random_enemy_object_ids supplied for custom summon action")
						breakpoint
						continue
					
					# newline if needed
					if returned_bbcode.length() > 0:
						returned_bbcode += "\n"
					
					# generate summoning bbcode then format with join
					returned_bbcode += "Summon: "
					var summoning_texts: Array[String] = []
					
					for enemy_id: String in random_enemy_object_ids:
						# add names and icons for each enemy
						var enemy_data: EnemyData = Global.get_enemy_data(enemy_id)
						var summoning_text: String = "{0} [img width={1}]{2}[/img]".format([enemy_data.enemy_name, BBCODE_EMBEDDED_IMAGE_WIDTH, enemy_data.enemy_texture_path])
						summoning_texts.append(summoning_text)
					
					returned_bbcode += ", ".join(summoning_texts)
					
				# statuses
				Scripts.ACTION_APPLY_STATUS:
					# get status parameters
					var action_target: int = action_data.get("target_override", BaseAction.TARGET_OVERRIDES.PLAYER)
					var status_effect_object_id: String = action_data.get("status_effect_object_id", "")
					var status_charge_amount: int = action_data.get("status_charge_amount", 1)
					# invalid status
					if status_effect_object_id == "":
						DebugLogger.log_error("EnemyIntentData: No status_effect_object_id supplied for custom status action")
						breakpoint
						continue
					
					var status_effect_data: StatusEffectData = Global.get_status_effect_data(status_effect_object_id)
					if status_effect_data == null:
						DebugLogger.log_error("EnemyIntentData: Invalid status effect ID {0} supplied for custom status action".format([status_effect_object_id]))
						breakpoint
						continue
					
					# get texture from charge amount
					var status_texture_path: String = status_effect_data.get_status_effect_texture_path(status_charge_amount)
					if status_texture_path == "":
						DebugLogger.log_warning("EnemyIntentData: No provided status texture for {0}".format([status_effect_object_id]))
						breakpoint
						continue
					
					# determine if buffing self or debuffing player
					# buffing enemies
					if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.BUFF:
						if action_target == BaseAction.TARGET_OVERRIDES.PARENT or action_target == BaseAction.TARGET_OVERRIDES.ALL_ENEMIES:
							if returned_bbcode.length() > 0:
								returned_bbcode += "\n" # newline
							returned_bbcode += "Gain {0}[img width={1}]{2}[/img]".format([status_charge_amount, BBCODE_EMBEDDED_IMAGE_WIDTH, status_texture_path])
					# debuffing player
					if status_effect_data.status_effect_type == StatusEffectData.STATUS_EFFECT_TYPES.DEBUFF:
						if action_target == BaseAction.TARGET_OVERRIDES.PLAYER:
							if returned_bbcode.length() > 0:
								returned_bbcode += "\n" # newline
							returned_bbcode += "Inflict {0}[img width={1}]{2}[/img]".format([status_charge_amount, BBCODE_EMBEDDED_IMAGE_WIDTH, status_texture_path])
	
	return returned_bbcode
