# tooltip displaying info on a single keyword
# generated by KeywordContainer
extends PanelContainer

const FONT_SIZE: int = 14
const EMBEDDED_IMAGE_SIZE: int = 24

@onready var keyword_rich_text_label: RichLabelAutoSizer = $KeywordRichTextLabel

func init(keyword_object_id: String) -> void:
	var keyword_data: KeywordData = Global.get_keyword_data(keyword_object_id)
	if keyword_data == null:
		DebugLogger.log_error("KeywordTooltip.init(): No keyword of id \"{0}\" found".format([keyword_object_id]))
	else:
		var keyword_bbcode: String = ""
		
		# keyword name
		keyword_bbcode = keyword_data.keyword_name
		
		# prepend status image if it exists
		var keyword_status_effect_id: String = keyword_data.keyword_status_effect_id
		if keyword_status_effect_id != "":
			var status_effect_data: StatusEffectData = Global.get_status_effect_data(keyword_status_effect_id)
			if status_effect_data == null:
				breakpoint
				DebugLogger.log_error("KeywordTooltip.init(): Invald keyword_status_effect_id of \"{0}\"".format([keyword_status_effect_id]))
			else:
				keyword_bbcode = "[img width={0}]{1}[/img] {2}".format([EMBEDDED_IMAGE_SIZE, status_effect_data.status_effect_texture_path, keyword_bbcode])
		
		# append keyword text
		keyword_bbcode = "{0}\n{1}".format([keyword_bbcode, keyword_data.keyword_text_bb_code])
		
		# force the font to a certain size
		keyword_bbcode = "[font_size={0}]{1}[/font_size]".format([FONT_SIZE, keyword_bbcode])
		keyword_rich_text_label.set_bbcode(keyword_bbcode)
	
		# this must be called deferred to force the rich text to not get clipped
		keyword_rich_text_label.set_deferred("fit_content", true)
