extends Control

@onready var victory_label: Label = %VictoryLabel
@onready var defeat_label: Label = %DefeatLabel
## Displays either VICTORY_MESSAGE or EventData.event_death_message_bbcode
@onready var end_run_message_label: RichTextLabel = %EndRunMessageLabel
## Displays formatted stats
@onready var stats_summary_autosize_label: RichLabelAutoSizer = %StatsSummaryAutosizeLabel

@onready var end_run_button = $EndRunButton

var player_run_end_state: int = Global.RUN_ENDS.QUIT # store if the player won or lost in the ui

const VICTORY_MESSAGE: String = "U R WINNER"

## Text formatting to populate with RunStatsData numbers
## Formatted as a grid with newlines and tabs and the end of the string appended with the given stat number
const SUMMARY_TEMPLATE: Dictionary[String, String] =  {
	"Standard Fights": "COMBAT_STANDARD_COUNT",
	"Minibosses": "COMBAT_MINIBOSS_COUNT",
	"Bosses": "COMBAT_BOSS_COUNT",
	"Times Rested": "REST_REST_COUNT",
	"Times Upgraded": "REST_UPGRADE_CARDS_COUNT",
	"Money Gained": "MONEY_GAINED_AMOUNT",
	"Cards Played": "CARDS_PLAYED",
	"Damage Taken": "PLAYER_DAMAGED_AMOUNT",
	"Damage Done": "ENEMY_DAMAGED_CAPPED_AMOUNT",
}
const SUMMARY_COLUMN_COUNT: int = 3

## The RunStatsData stat string names you want to pull into the SUMMARY_TEMPLATE.
## NOTE: Some of these are generated by RestActionData.rest_action_stat_name, some are from 
## CombatStatsData.STATS, and some are from RunStatsData.STATS.
## They're all aggregated into RunStatsData.
const SUMMARY_STAT_NAMES: Array[String] = [
	"COMBAT_STANDARD_COUNT", "COMBAT_MINIBOSS_COUNT", "COMBAT_BOSS_COUNT",
	"REST_REST_COUNT", "REST_UPGRADE_CARDS_COUNT", "MONEY_GAINED_AMOUNT",
	"CARDS_PLAYED", "PLAYER_DAMAGED_AMOUNT", "ENEMY_DAMAGED_CAPPED_AMOUNT",
]

func _ready():
	end_run_button.button_up.connect(_on_end_run_button_up)
	Signals.combat_ended.connect(_on_combat_ended)
	Signals.run_started.connect(_on_run_started)
	Signals.run_ended.connect(_on_run_ended)
	Signals.run_victory.connect(_on_run_victory)
	Signals.player_death_animation_finished.connect(_on_player_death_animation_finished)

## Pulls stats and then inserts and formats the text into a rich text
func generate_run_summary_text() -> void:
	# error out if no stats found
	var current_run_stats: RunStatsData = StatsHandler.current_run_stats
	if current_run_stats == null:
		breakpoint
		DebugLogger.log_error("RunSummaryOverlay: Current run stats not detected")
		stats_summary_autosize_label.set_bbcode("[color=red]Current run stats not found[/color]")
		
	# All the cells concatenated together, since godot rich text tables
	# don't format as an X by X grid but by a single line of cells
	var summary_cell_text: String = ""
	for summary_stat_text: String in SUMMARY_TEMPLATE:
		# pull stat name and value
		var run_stat_name: String = SUMMARY_TEMPLATE[summary_stat_text]
		var stat_value: int = current_run_stats.get_run_total_stat(run_stat_name)
		# format text into a cell
		var cell_text: String = "[cell]{0}: {1}[/cell]".format([summary_stat_text, stat_value])
		summary_cell_text += cell_text
		
	# create table and fill it with cells
	var generated_bbcode: String = "[center][table={0}]{1}[/table][/center]".format([SUMMARY_COLUMN_COUNT, summary_cell_text])
	# set the text to display it
	stats_summary_autosize_label.set_bbcode(generated_bbcode)

func _on_combat_ended():
	if Global.is_end_of_run():
		visible = true
		Signals.run_victory.emit()

func _on_run_started():
	visible = false
		
func _on_run_ended():
	visible = false
	
func _on_run_victory():
	victory_label.visible = true
	defeat_label.visible = false
	end_run_message_label.text = VICTORY_MESSAGE
	generate_run_summary_text()
	visible = true
	player_run_end_state = Global.RUN_ENDS.VICTORY

# loss of a run
func _on_player_death_animation_finished(_player: Player):
	victory_label.visible = false
	defeat_label.visible = true
	
	var event_data: EventData = Global.get_player_event_data()
	if event_data != null:
		end_run_message_label.parse_bbcode(event_data.event_death_message_bbcode)
	
	generate_run_summary_text()
	visible = true
	player_run_end_state = Global.RUN_ENDS.LOSS

func _on_end_run_button_up():
	visible = false
	Global.end_run(player_run_end_state)
